[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-capture = "1.4.2"
device_query = "1.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
dotenv = "0.15"
arboard = "3.2"
enigo = "0.1"
